### ISSUE TITLE
Relation to version 2?

### ISSUE THREAD

**Issue by binarykitchen** [darealshinji/mkv-extractor-qt5#2]
Hi there

I spotted a second version, https://sourceforge.net/projects/mkvextractgui-2/

Is there a relation mkv-extractor-qt5 is having to this one? Is yours still active?

**Comment by darealshinji** [comment]
There's no relation at all (it even has a different name). This is just a personal mirror, the original author publishes his releases on [Launchpad](https://launchpad.net/~hizo/+archive/ubuntu/mkv-extractor-gui) and can be contacted by email: hizo@free.fr
