### ISSUE TITLE
Unable to extract sub for srt conversion

### ISSUE THREAD

**Issue by binarykitchen** [darealshinji/mkv-extractor-qt5#3]
When I have opened an mkv file and attempt to extract a `.sub` track with the middle button to have it converted to `.srt` and execute that, nothing happens. The whole UI gets frozen. There is no feedback, no visual error saying what's wrong.

**Comment by darealshinji** [comment]
As far as I know that requires [Qtesseract5](https://github.com/darealshinji/Qtesseract5). As for the bug, I think you should report it to the original author: hizo@free.fr

**Comment by binarykitchen** [comment]
@darealshinji thanks, will email him and point to this thread
