### ISSUE TITLE
sync with v5.5.5a

### ISSUE THREAD

**Issue by sl1pkn07** [darealshinji/mkv-extractor-qt5#4]
seems this project is updated by upstream

https://launchpadlibrarian.net/355006673/mkv-extractor-qt5_5.5.5a-0~bionic_source.changes

also, please can you make this fix?

https://forum.ubuntu-fr.org/viewtopic.php?id=1508741&p=7 (comment #166)

greetings

**Comment by darealshinji** [comment]
Thanks for the heads-up. I will update it soon.

**Comment by darealshinji** [comment]
Updated and added the fix.

**Comment by sl1pkn07** [comment]
thanks man
